# Generated by Django 5.0.2 on 2024-02-18 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('type', models.CharField(default='MCQ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.PositiveIntegerField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.choices')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.question')),
            ],
        ),
        migrations.CreateModel(
            name='RoundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_is_correct_answer', models.BooleanField(default=False)),
                ('marks_awarded', models.PositiveIntegerField()),
                ('choice_made_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.choices')),
                ('question_selected_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.question')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.round')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.team')),
            ],
        ),
    ]
