# Generated by Django 4.2.10 on 2024-02-20 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('type', models.CharField(choices=[('MCQ', 'MCQ Type Questions'), ('SA', 'Short Answer Type Questions')], default='MCQ', max_length=3)),
                ('answer', models.CharField(default='', max_length=255, null=True)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True)),
                ('stop', models.DateTimeField(default=None, null=True)),
                ('round_name', models.CharField(default='', max_length=255)),
                ('duration', models.PositiveIntegerField(default=15)),
                ('state', models.CharField(choices=[('Ongoing', 'Round is ongoing'), ('Completed', 'Round has ended'), ('Inaccessible', 'Round is inaccessble to all participants')], default='Inaccessible', max_length=12)),
                ('question_time', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_selected_text', models.CharField(default=None, max_length=255, null=True)),
                ('choice_is_correct_answer', models.BooleanField(default=False, null=True)),
                ('marks_awarded', models.PositiveIntegerField(null=True)),
                ('question_selected_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.question')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.round')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.team')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='round_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_system.round'),
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_system.question')),
            ],
        ),
    ]
