# Generated by Django 4.2.10 on 2024-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0002_remove_team_name_remove_team_password_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
