# Generated by Django 4.2.10 on 2024-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
