# Generated by Django 4.2.10 on 2024-02-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0003_team_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logged_in',
        ),
    ]
