# Generated by Django 4.2.10 on 2024-02-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0003_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='choice_id',
        ),
    ]
