# Generated by Django 4.2.10 on 2024-02-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0004_remove_answers_choice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundinfo',
            name='choice_is_correct_answer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roundinfo',
            name='choice_made_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_system.choices'),
        ),
        migrations.AlterField(
            model_name='roundinfo',
            name='marks_awarded',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
