# Generated by Django 4.2.10 on 2024-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0004_remove_team_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logged_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
