# Generated by Django 4.2.10 on 2024-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system', '0005_alter_roundinfo_choice_is_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
